version: 0.2

env:
  variables:
    TF_VERSION: "0.12.29"

phases:

  install:
    commands:
      - cd /usr/bin
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - unzip -o terraform.zip
      - pip install --quiet boto3 pyyaml

  build:
    commands:    
      - cd "$CODEBUILD_SRC_DIR"
      - sed -i -e "s/{{ENV}}/$TF_VAR_ENV/" terraform.tf
      - terraform init -no-color
      - terraform $TF_ACTION -no-color -var-file="config/$TF_VAR_ENV.tfvars"
  post_build:
    commands:
      - echo "terraform $TF_ACTION on $TF_VAR_ENV completed on `date`"
